name: Compile artifacts

on:
  push:
    branches:
        - 'main'
        - 'releases/**'
        - 'master'
    tags:
        - '**'
  # pull_request:
    # types: [opened, reopened]
  # workflow_dispatch:
  release:
    types: [published]

jobs:
  Symbian:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Fill API secrets
        shell: cmd
        env:
          TG_API_HASH: ${{ secrets.KUTEGRAM_APP_HASH }}
          TG_API_ID: ${{ secrets.KUTEGRAM_APP_ID }}
        run: |
          fillSecrets.bat
      
      - name: Create certificates files
        shell: cmd
        env:
          KUTEGRAM_CERT: ${{ secrets.KUTEGRAM_CERT }}
          KUTEGRAM_CERT_KEY: ${{ secrets.KUTEGRAM_CERT_KEY }}
        run: |
          echo %KUTEGRAM_CERT% | openssl base64 -d -A -out selfsigned.cer
          echo %KUTEGRAM_CERT_KEY% | openssl base64 -d -A -out selfsigned.key
      
      - name: Compile sources and sign package
        shell: cmd
        run: |
          buildSymbian_signed.bat

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: Symbian^1 installer
          path: Kutegram.sis
      
      - name: Send to CI channel
        shell: cmd
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          UPLOAD_FILE: Kutegram.sis
          COMMIT_AUTHOR: ${{ github.event.commits[0].author.name }}
          COMMIT_USERNAME: ${{ github.event.commits[0].author.username }}
          COMMIT_SHA: ${{ github.event.commits[0].id }}
          COMMIT_REPO: ${{ github.event.repository.full_name }}
          COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
          BOT_CHANNEL: ${{ secrets.TELEGRAM_TO }}
        run: |
          pip install requests
          python telegram-ci.py
