name: Compile artifacts

on:
  push:
    branches:
        - 'main'
        - 'releases/**'
        - 'master'
    tags:
        - '**'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Symbian:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Fill API secrets
        shell: cmd
        env:
          TG_API_HASH: ${{ secrets.KUTEGRAM_APP_HASH }}
          TG_API_ID: ${{ secrets.KUTEGRAM_APP_ID }}
        run: |
          fillSecrets.bat
      
      - name: Compile sources
        shell: cmd
        run: |
          buildSymbian.bat

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: Symbian^1 installer
          path: Kutegram.sis
      
      - name: Send to CI channel
        shell: cmd
        run: |
          pip install requests
          pip install sys
          python telegram-ci.py ${{ secrets.TELEGRAM_TOKEN }} Kutegram.sis ${{ github.event.commits[0].author }} ${{ github.sha }} ${{ github.repository }} ${{ github.event.commits[0].message }} ${{ secrets.TELEGRAM_TO }}
