# This is a basic workflow to help you get started with Actions

name: Symbian build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Secret test
        shell: cmd
        env:
          KUTEGRAM_APP_HASH: ${{ secrets.KUTEGRAM_APP_HASH }}
          KUTEGRAM_APP_ID: ${{ secrets.KUTEGRAM_APP_ID }}
        run: |
          echo %KUTEGRAM_APP_HASH%
          echo %KUTEGRAM_APP_ID%
    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Fill API secrets
        shell: cmd
        env:
          TG_API_HASH: ${{ secrets.KUTEGRAM_APP_HASH }}
          TG_API_ID: ${{ secrets.KUTEGRAM_APP_ID }}
        run: |
          fillSecrets.bat
      
      - name: Compile sources
        shell: cmd
        run: |
          buildSymbian.bat

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: SIS file
          path: Kutegram.sis
